name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "15 11 3 1-9,11-12 *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/uv-upgrade.yml@a512edd4814b803be6a9b9e1cb0012ad715196db # v1
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
